version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/BOOKINGAUTH
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
