version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: maryam5/mern-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_DB=mongodb://mongo:27017/BOOKINGAUTH

  frontend:
    image: maryam5/mern-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo-data:
